import { getCertsByAddress } from "@/src/lib/contract";
import { CertCard } from "@/src/components/learn/CertCard";
import { shortenAddress } from "@/src/utils/shortenAddress";
import { ShieldCheck, Award } from "lucide-react";
import { VerifyHeader } from "@/src/components/ui/VerifyHeader";

interface Props {
  params: Promise<{ address: string }>;
}

export default async function VerifyPage({ params }: Props) {
  const { address } = await params;

  let certs: Awaited<ReturnType<typeof getCertsByAddress>> = [];
  let fetchError = false;

  if (/^0x[0-9a-fA-F]{40}$/.test(address)) {
    try {
      certs = await getCertsByAddress(address);
    } catch {
      fetchError = true;
    }
  }

  return (
    <div className="min-h-screen se-grid pt-14 relative overflow-hidden" style={{ background: "var(--bg)" }}>
      {/* Glow overlay */}
      <div className="pointer-events-none absolute inset-0 se-hero-bg" style={{ opacity: 0.5 }} />

      {/* Nav */}
      <VerifyHeader />

      <main className="max-w-5xl mx-auto px-4 py-12 w-full animate-fade-in">
        <style>{`
          @keyframes scan {
            0% { transform: translateY(0); opacity: 0; }
            10% { opacity: 1; }
            90% { opacity: 1; }
            100% { transform: translateY(180px); opacity: 0; }
          }
          .animate-scan {
            animation: scan 3s linear infinite;
          }
        `}</style>

        {/* Header */}
        <div className="mb-10 flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-white/5 pb-6">
          <div>
            <span className="se-label">Verification Portal</span>
            <div className="flex flex-wrap items-center gap-3 mt-1.5">
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                Credentials for{" "}
                <span className="text-cyan-400" style={{ fontFamily: "var(--font-mono)" }}>
                  {shortenAddress(address, 6)}
                </span>
              </h1>
              {certs.length > 0 && (
                <span
                  className="flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full"
                  style={{
                    background: "rgba(16,185,129,0.1)",
                    border: "1px solid rgba(16,185,129,0.25)",
                    color: "#34d399",
                    boxShadow: "0 0 15px rgba(16,185,129,0.15)"
                  }}
                >
                  <ShieldCheck size={12} className="animate-pulse" />
                  Verified Holder
                </span>
              )}
            </div>
            <p className="text-sm text-white/50 mt-1">
              Cryptographically verified soulbound certificates generated by AI curriculum evaluations.
            </p>
          </div>
          
          <div className="text-left md:text-right shrink-0">
            <span className="text-[10px] uppercase font-bold tracking-wider text-white/30 block">Network Anchor</span>
            <span className="text-xs font-mono font-semibold text-white/70 block mt-0.5">Base Sepolia Testnet</span>
          </div>
        </div>

        {fetchError && (
          <div
            className="p-4 rounded-[8px] border mb-6"
            role="alert"
            style={{ background: "rgba(239,68,68,0.08)", borderColor: "rgba(239,68,68,0.2)" }}
          >
            <p className="text-sm text-red-400">Failed to load certificates. Check the cryptographic address and try again.</p>
          </div>
        )}

        {certs.length === 0 && !fetchError ? (
          <div
            className="flex flex-col items-center gap-6 py-20 rounded-2xl border border-white/5 relative overflow-hidden group max-w-2xl mx-auto"
            style={{ background: "rgba(10, 10, 16, 0.4)", backdropFilter: "blur(12px)" }}
          >
            {/* Ambient scanner effect */}
            <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-cyan-500 to-transparent animate-scan" />
            <div className="absolute -inset-10 bg-radial-gradient from-cyan-500/5 to-transparent blur-2xl opacity-50 pointer-events-none" />

            <div className="relative flex items-center justify-center w-16 h-16 rounded-full border border-white/10 bg-white/5 shadow-[0_0_15px_rgba(255,255,255,0.02)]">
              <Award size={32} className="text-white/20 group-hover:text-cyan-400 transition-colors duration-500" />
              <div className="absolute inset-0 rounded-full border border-cyan-500/20 animate-ping opacity-30" />
            </div>

            <div className="text-center space-y-2 max-w-sm px-4">
              <p className="text-white font-semibold text-lg">No Credentials Registered</p>
              <p className="text-white/40 text-xs leading-relaxed">
                This cryptographic address does not hold any verified soulbound credentials on Base Sepolia.
              </p>
              <div className="pt-2">
                <span className="inline-block font-mono text-[10px] bg-black/40 px-3 py-1 rounded-[6px] border border-white/5 text-white/50 tracking-wider">
                  {shortenAddress(address)}
                </span>
              </div>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {certs.map((cert) => (
              <div key={cert.tokenId} className="transition-all duration-300">
                <CertCard
                  cert={{ ...cert, learner: address }}
                  showShareLink
                />
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
